version: '3.8'

services:
  app:
    image: unite-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"