apiKey=api?

vacation.upload.directory=D:/uploads/unite/vacation
profile.upload.directory=D:/uploads/unite/profile

project.upload.directory=D:/uploads/unite/project

post.upload.directory=D:/uploads/unite/board/post
postComment.upload.directory=D:/uploads/unite/board/postComment
