apiKey=api?
vacation.upload.directory=D:/uploads/unite/vacation
profile.upload.directory=D:/uploads/unite/profile

projectdone.upload.directory=D:/uploads/unite/project/ProjectDone
projecttask.upload.directory=D:/uploads/unite/project/ProjectTask
post.upload.directory=D:/uploads/unite/board/post
postComment.upload.directory=D:/uploads/unite/board/postComment
